version: "3.9"

services:

  broker:
    build: { context: ../.., dockerfile: src/simulation_broker/Dockerfile }
    ports:
      - "3000:80"

  user_model:
    build: { context: ../.., dockerfile: src/user_model/simple/Dockerfile }

  scenario_generator:
    build: { context: ../.., dockerfile: src/scenario/generator/Dockerfile }

  scenario_commuter:
    build: { context: ../.., dockerfile: src/scenario/commuter/Dockerfile }

  ondemand:
    build: { context: ../.., dockerfile: src/base_simulators/ondemand/Dockerfile }
    ports:
      - "3002:80"

  oneway:
    build: { context: ../.., dockerfile: src/base_simulators/oneway/Dockerfile }
    ports:
      - "3003:80"

  planner:
    build: { context: ../.., dockerfile: src/planner/simple/Dockerfile }
    ports:
      - "3010:80"

  walking:
    build: { context: ../.., dockerfile: src/base_simulators/walking/Dockerfile }

  evaluation:
    build: { context: ../.., dockerfile: src/evaluation/simple/Dockerfile }
    ports:
      - "3020:80"
