version: "3.9"

services:

  broker:
    build: { context: ../.., dockerfile: src/simulation_broker/Dockerfile }
    ports:
      - "3000:80"

  user_model:
    build: { context: ../.., dockerfile: src/user_model/simple/Dockerfile }

  scenario_historical:
    build: { context: ../.., dockerfile: src/scenario/historical/Dockerfile }

  scheduled:
    build: { context: ../.., dockerfile: src/base_simulators/scheduled/Dockerfile }
    ports:
      - "3001:80"

  route_deviation:
    build: { context: ../.., dockerfile: src/base_simulators/routedeviation/Dockerfile }
    ports:
      - "3002:80"

  planner:
    build: { context: ../.., dockerfile: src/planner/opentripplanner/Dockerfile }
    ports:
      - "3010:80"

  walking:
    build: { context: ../.., dockerfile: src/base_simulators/walking/Dockerfile }
