services:
  broker:
    build: { context: ../.., dockerfile: src/simulation_broker/Dockerfile }
    ports:
      - "3000:80"

  walking:
    build: { context: ../.., dockerfile: src/base_simulators/walking/Dockerfile }

  user_model:
    build: { context: ../.., dockerfile: src/user_model/simple/Dockerfile }

  scenario_commuter:
    build: { context: ../.., dockerfile: src/scenario/commuter/Dockerfile }

  scheduled:
    build: { context: ../.., dockerfile: src/base_simulators/scheduled/Dockerfile }
    ports:
      - "3001:80"

  planner:
    build: { context: ../.., dockerfile: src/planner/opentripplanner/Dockerfile }
    ports:
      - "3010:80"
