name: compliance checks

on:
  push:
    branches:
    paths: 'src/**'
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: main
    paths: 'src/**'
  workflow_dispatch:

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      subdirs: ${{ steps.set-subdir.outputs.target-list }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get src subdirectories
        id: set-subdir
        run: |
          list=`find ./src -name requirements.txt | sed -r "s/^(.*)requirements.txt/\1/g" | jq -R -s -c 'split("\n")[:-1]' | jq -c .`
          echo "target-list=$list" >> $GITHUB_OUTPUT
  check-license:
    runs-on: ubuntu-latest
    needs: set-matrix
    strategy:
      matrix:
        target: ${{ fromJson(needs.set-matrix.outputs.subdirs) }}
    steps:
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get allowed licence list
        working-directory: ci
        run: |
          LICENSE_LIST=$(awk '!/^\s*#/' allowed-license.lst | tr '\n' ';')
          echo "license=$LICENSE_LIST" >> $GITHUB_ENV
      - name: Install and run pip-licenses          
        working-directory: ${{ matrix.target }}
        run: |
          pip install -r requirements.txt
          pip install -U pip-licenses-cli
          pip-licenses --allow-only="${{ env.license }}"
